# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobuf import studentService_pb2 as protobuf_dot_studentService__pb2


class StudentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getStudentContactDetails = channel.unary_unary(
                '/StudentService/getStudentContactDetails',
                request_serializer=protobuf_dot_studentService__pb2.GetStudentContactRequest.SerializeToString,
                response_deserializer=protobuf_dot_studentService__pb2.GetStudentContactResponse.FromString,
                )
        self.getAllStudents = channel.unary_unary(
                '/StudentService/getAllStudents',
                request_serializer=protobuf_dot_studentService__pb2.GetAllStudentsRequest.SerializeToString,
                response_deserializer=protobuf_dot_studentService__pb2.GetAllStudentsResponse.FromString,
                )
        self.getStudentById = channel.unary_unary(
                '/StudentService/getStudentById',
                request_serializer=protobuf_dot_studentService__pb2.GetStudentByIdRequest.SerializeToString,
                response_deserializer=protobuf_dot_studentService__pb2.GetStudentByIdResponse.FromString,
                )
        self.saveStudent = channel.unary_unary(
                '/StudentService/saveStudent',
                request_serializer=protobuf_dot_studentService__pb2.SaveStudentRequest.SerializeToString,
                response_deserializer=protobuf_dot_studentService__pb2.SaveStudentResponse.FromString,
                )
        self.updateStudent = channel.unary_unary(
                '/StudentService/updateStudent',
                request_serializer=protobuf_dot_studentService__pb2.UpdateStudentRequest.SerializeToString,
                response_deserializer=protobuf_dot_studentService__pb2.UpdateStudentResponse.FromString,
                )
        self.deleteStudent = channel.unary_unary(
                '/StudentService/deleteStudent',
                request_serializer=protobuf_dot_studentService__pb2.DeleteStudentRequest.SerializeToString,
                response_deserializer=protobuf_dot_studentService__pb2.DeleteStudentResponse.FromString,
                )


class StudentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getStudentContactDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllStudents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStudentById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def saveStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getStudentContactDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.getStudentContactDetails,
                    request_deserializer=protobuf_dot_studentService__pb2.GetStudentContactRequest.FromString,
                    response_serializer=protobuf_dot_studentService__pb2.GetStudentContactResponse.SerializeToString,
            ),
            'getAllStudents': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllStudents,
                    request_deserializer=protobuf_dot_studentService__pb2.GetAllStudentsRequest.FromString,
                    response_serializer=protobuf_dot_studentService__pb2.GetAllStudentsResponse.SerializeToString,
            ),
            'getStudentById': grpc.unary_unary_rpc_method_handler(
                    servicer.getStudentById,
                    request_deserializer=protobuf_dot_studentService__pb2.GetStudentByIdRequest.FromString,
                    response_serializer=protobuf_dot_studentService__pb2.GetStudentByIdResponse.SerializeToString,
            ),
            'saveStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.saveStudent,
                    request_deserializer=protobuf_dot_studentService__pb2.SaveStudentRequest.FromString,
                    response_serializer=protobuf_dot_studentService__pb2.SaveStudentResponse.SerializeToString,
            ),
            'updateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.updateStudent,
                    request_deserializer=protobuf_dot_studentService__pb2.UpdateStudentRequest.FromString,
                    response_serializer=protobuf_dot_studentService__pb2.UpdateStudentResponse.SerializeToString,
            ),
            'deleteStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteStudent,
                    request_deserializer=protobuf_dot_studentService__pb2.DeleteStudentRequest.FromString,
                    response_serializer=protobuf_dot_studentService__pb2.DeleteStudentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StudentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StudentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getStudentContactDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/getStudentContactDetails',
            protobuf_dot_studentService__pb2.GetStudentContactRequest.SerializeToString,
            protobuf_dot_studentService__pb2.GetStudentContactResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllStudents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/getAllStudents',
            protobuf_dot_studentService__pb2.GetAllStudentsRequest.SerializeToString,
            protobuf_dot_studentService__pb2.GetAllStudentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getStudentById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/getStudentById',
            protobuf_dot_studentService__pb2.GetStudentByIdRequest.SerializeToString,
            protobuf_dot_studentService__pb2.GetStudentByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def saveStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/saveStudent',
            protobuf_dot_studentService__pb2.SaveStudentRequest.SerializeToString,
            protobuf_dot_studentService__pb2.SaveStudentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/updateStudent',
            protobuf_dot_studentService__pb2.UpdateStudentRequest.SerializeToString,
            protobuf_dot_studentService__pb2.UpdateStudentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/deleteStudent',
            protobuf_dot_studentService__pb2.DeleteStudentRequest.SerializeToString,
            protobuf_dot_studentService__pb2.DeleteStudentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
